### PR TITLE
Discourage ruining of brand colors

### PR DESCRIPTION
**Pull request by kornelski**
Some brands have very specific (trademark) colors associated with them, such as Milka, T-Mobile. These colors completely lose their special meaning if they're changed.

For example, if you darken FT's brand "salmon pink" it's going to look, ekhm, _crappy_, quite literally.

AFAIK current implementations in Android and Windows don't change the color, so it would be good to codify that in the spec.

### CODE REVIEW

**Comment by Tigt** [comment]
Android does change the color slightly when multiple tabs are opened, by gradually lightening the color for each stacked tab.

**Comment by pornel** [comment]
Task switcher in Lollipop adds shadow on top of tabs in the background. I think that's fine (the color stays the same in relation to other colors, as humans are good at recognizing colors in context).

Perhaps the spec should add that shadows and bevels are ok?

**Comment by domenic** [comment]
Sorry that I didn't see this before moving it to the spec. I think it would be pretty reasonable to add a "User agents should generally avoid such adjustments, for [something about how brands are important] reasons" and to change the example to a different one (like Android's), perhaps with a counterexample like in this PR as well.

If you're still interested in this, would you mind filing a PR over at whatwg/html? If you'd rather we do it, that's fine too, since it's our fault for dropping the ball on getting to this.

**Comment by kornelski** [comment]
I'll do another PR when I have time.

**Comment by domenic** [comment]
Moved to https://github.com/whatwg/html/issues/803

**Pull request closed without merging**
