### PR TITLE
Linked to "Parse a component value"

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by annevk** [comment]
Is this repository dead?

**Comment by marcoscaceres** [comment]
On Saturday, May 9, 2015, Anne van Kesteren <notifications@github.com>
wrote:

> Is this repository dead?
>

Hella no! Implemented in Chrome, fxos. Manifest also relies on this ATM.

**Comment by annevk** [comment]
I see. Can we fold this into HTML proper somehow?

**Comment by marcoscaceres** [comment]
On Saturday, May 9, 2015, Anne van Kesteren <notifications@github.com>
wrote:

> I see. Can we fold this into HTML proper somehow?
>
That would be great. I'll file a bug on HTML to fold this in on Monday.

**Comment by marcoscaceres** [comment]
@annevk, filed: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28623

**Comment by annevk** [comment]
Ta!

**Pull request merged**
